
# SEO settings
title: "Karthik's"
title2: "Humble Adobe" # default: ""
description: "A place where my thoughts can roam free."
keywords: "Jekyll, theme"
url: http://pyrito.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "pyrito"
twitter_username: "pyr1to"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Karthik Velayutham"
  job      : "Turing Scholar at The University of Texas at Austin"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : pyrito@gmail.com
  url      : http://heiswayi.pyrito.io
  github   : http://github.com/pyrito
  twitter  : http://twitter.com/pyr1to
  facebook : https://www.facebook.com/
  linkedin : http://linkedin.com/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@pyrito"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug: projects
    title: Projects

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
