title: 'katthicktv'
description: "My portfolio built with a jekyll theme"
baseurl: "/"
url: "https://pyrito.github.io"

header_pages:
  - index.md
  - about.md
  - blog.md
  - contact.md

style: light

footer: 'made with ❤️ in austin, tx'

# Build settings
markdown: kramdown
